{{- if ne .Values.dynamicEnv.normal.clients_fqdn "" }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Values.namespace }}-certificate
  namespace: custom-domain-ingressroutes
spec:
  secretName: {{ .Values.namespace }}-tls-cert
  issuerRef:
    name: custom-domain-issuer
  commonName: {{ .Values.dynamicEnv.normal.clients_fqdn }}
  dnsNames:
  - {{ .Values.dynamicEnv.normal.clients_fqdn }}
{{- end }}
