apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: {{ template "phpcomposer.fullname" . }}-root-ingress
  namespace: default
spec:
  virtualhost:
    fqdn: {{ .Values.fqdn }}
    tls:
      secretName: {{ .Values.tls }}
  routes:
    - match: /
      timeoutPolicy:
        request: {{ .Values.TimeOutPolicy.request }}
      retryPolicy:
        count: {{ .Values.RetryPolicy.count }}
        perTryTimeout: {{ .Values.RetryPolicy.perTryTimeout }}
      delegate:
        name: {{ template "phpcomposer.fullname" . }}-ingress
        namespace: {{ .Values.namespace }}
---

apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: {{ template "phpcomposer.fullname" . }}-ingress

spec:
  routes:
    - match: /
      services:
        - name: {{ template "phpcomposer.fullname" . }}
          port: 80
          healthCheck:
            path: {{ .Values.HealthCheck.path }}
            intervalSeconds: {{ .Values.HealthCheck.intervalSeconds }}
            timeoutSeconds: {{ .Values.HealthCheck.timeoutSeconds }}
            unhealthyThresholdCount: {{ .Values.HealthCheck.unhealthyThresholdCount }}
            healthyThresholdCount: {{ .Values.HealthCheck.healthyThresholdCount }}

