apiVersion: v1
kind: Service
metadata:
  name: {{ include "phpcomposer.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "phpcomposer.selectorLabels" . | nindent 4 }}
