{{- if ne .Values.clients_fqdn "" }}
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: {{ template "ghost.fullname" . }}-custom-domain-root-ingress
  namespace: custom-domain-ingressroutes
  annotations:
    cert-manager.io/cluster-issuer:  {{ .Values.namespace}}-issuer 
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"
spec:
  virtualhost:
    fqdn: {{ .Values.clients_fqdn }}
    tls:
     secretName: {{ .Values.namespace}}-tls-cert
  routes:
    - match: /
      timeoutPolicy:
        request: {{ .Values.TimeOutPolicy.request }}
      retryPolicy:
        count: {{ .Values.RetryPolicy.count }}
        perTryTimeout: {{ .Values.RetryPolicy.perTryTimeout }}
      delegate:
        name: {{ template "ghost.fullname" . }}-custom-domain-ingress
        namespace: {{ .Values.namespace }}
    - match: /phpmyadmin/
      timeoutPolicy:
        request: {{ .Values.TimeOutPolicy.request }}
      retryPolicy:
        count: {{ .Values.RetryPolicy.count }}
        perTryTimeout: {{ .Values.RetryPolicy.perTryTimeout }}
      delegate:
        name: custom-domain-phpmyadmin-ingress
        namespace: {{ .Values.namespace }}
{{- end }}
---
{{- if ne .Values.clients_fqdn "" }}
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: {{ template "ghost.fullname" . }}-custom-domain-ingress

spec:
  routes:
    - match: /
      services:
        - name: {{ template "ghost.fullname" . }}
          port: 80
          healthCheck:
            path: {{ .Values.HealthCheck.path }}
            intervalSeconds: {{ .Values.HealthCheck.intervalSeconds }}
            timeoutSeconds: {{ .Values.HealthCheck.timeoutSeconds }}
            unhealthyThresholdCount: {{ .Values.HealthCheck.unhealthyThresholdCount }}
{{- end }}
