apiVersion: v1
appVersion: 0.1.0
description: A Library Helm Chart for grouping common logic between bitnami charts.
  This chart is not deployable by itself.
engine: gotpl
icon: https://bitnami.com/downloads/logos/bitnami-mark.png
keywords:
- common
- helper
- template
- function
- bitnami
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: common
sources:
- https://github.com/bitnami/charts
version: 0.2.0
