apiVersion: batch/v1
kind: Job
metadata:
  name: dns
spec:
  template:
    spec:
      containers:
      - name: zerone-dns-job
        image: google/cloud-sdk
        command: ["/bin/sh"]
        args: ["-c", "gcloud auth activate-service-account --key-file /app/dns-cred-gcp.json; gcloud config set project zerone-devops-labs; gcloud dns record-sets transaction start --zone={{ .Values.zone_name }}; gcloud dns record-sets transaction add '{{ .Values.zone }}' --name={{ .Values.fqdn }} --ttl=14400 --type=CNAME --zone={{ .Values.zone_name }} ; gcloud dns record-sets transaction execute --zone={{ .Values.zone_name }}"]
        volumeMounts:
        - name: dns-cred
          mountPath: /app/dns-cred-gcp.json
          subPath: zerone-cloud-dns.json 
      restartPolicy: Never
      volumes:
        - name: dns-cred
          secret:
            secretName: zerone-cloud-dns
  backoffLimit: 4

