apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: {{ template "opencart.fullname" . }}-root-ingress
  namespace: default
spec:
  virtualhost:
    fqdn: {{ .Values.fqdn }}
    tls:
      secretName: {{ .Values.tls }}
  routes:
    - match: /
      delegate:
        name: {{ template "opencart.fullname" . }}-ingress
        namespace: {{ .Values.namespace }}

---

apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: {{ template "opencart.fullname" . }}-ingress

spec:
  routes:
    - match: /
      services:
        - name: {{ template "opencart.fullname" . }}
          port: 80
