apiVersion: v1
kind: Service
metadata:
  name: {{ template "node.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.TargetPort }}
      protocol: TCP
  selector:
     {{- include "node.labels" . | nindent 4 }}
